### ISSUE TITLE
restart option for stacks

### ISSUE THREAD

**Issue by mrtnbr** [brhahlen/dc#10]
I cannot restart stacks with dc, only containers. It would be nice to also be able to restart stacks.

**Comment by brhahlen** [comment]
@mrtnbr What are your thoughts?
The current implementation for `restart` of services is that it stops the container, removes it, and then brings it up again. (There's a separate improvement to be had there...)

For a stack, would that "just" do a restart (i.e.: `docker-compose restart <STACKNAME>`) or a `down`/`up` combination?

**Comment by brhahlen** [comment]
Addition: I've added #20 where further options to commands will be added. For now, focus on the MVP (Minimum Viable Product).

**Comment by brhahlen** [comment]
For now I've implemented this using `restart-stack` as the command in `dc`, which "just" does a `restart` on the stack itself.
I think that is more clean.
For services, I think it is more viable to allow the removal of the container by default, but for a stack this seems more intrusive.
