### ISSUE TITLE
Multiple "File is too old, refreshing" 

### ISSUE THREAD

**Issue by mrtnbr** [brhahlen/dc#14]
user@hostname:~/docker/docker-compose$ dc restart watchtower
Restarting the following service(s): watchtower
Stopping the following service(s): watchtower
File is too old, refreshing
File is too old, refreshing
File is too old, refreshing
File is too old, refreshing
File is too old, refreshing
Stopping watchtower ... done
Going to remove watchtower
Removing watchtower ... done
Starting the following service(s): watchtower
Creating watchtower ... done

**Comment by brhahlen** [comment]
Ah, yes.
This is due to testing, will remove this, but added #15 as an enhancement to be able to add more verbose output later.
