### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by oxr463** [brhahlen/dc#35]
Why would I use this instead of docker-compose? What would that look like?

**Comment by brhahlen** [comment]
So, for `docker-compose` (or `docker-compose`) you would have to go to the directory that the docker-compose.yml file is in and run the commands from there.
With `dc`, you can run commands from wherever you are on the prompt.

So, for instance, you could run `dc restart nginx` and `dc` would restart the nginx container like that.

Does that help?

**Comment by oxr463** [comment]
Ah... Yes, that sounds awesome!

How does it know where the `docker-compose.yml` file is located?

**Comment by brhahlen** [comment]
When installing, you specify a `DC_DIR` variable, which is stored in your `.bashrc`
The `DC_DIR` contains subdirectories (stacks) with the different `docker-compose.yml` files

For instance:
<DC_DIR>/1-backends/docker-compose.yml
<DC_DIR>2-system/docker-compose.yml

Makes sense?

**Comment by oxr463** [comment]
Ah... Yes, thank you for explaining.

**Comment by brhahlen** [comment]
If alright with you, I'll close this issue.
I've created a new issue (#44) for this.
