### ISSUE TITLE
Feature request/discussion: dc command to get a shell inside a container

### ISSUE THREAD

**Issue by mrtnbr** [brhahlen/dc#65]
I find myself typing stuff like ```docker exec -it 05-backup-db-backup-1 bash``` a lot lately. A dc command to get a shell in a container might be nice to have!

Docker Debug exists (https://docs.docker.com/reference/cli/docker/debug/) but is hidden behind a paywall.

**Comment by brhahlen** [comment]
Will look into it.
Probably will default to `/bin/sh`, as not all containers have `bash` installed.
