### ISSUE TITLE
"dc shell" glitches when using Ctrl-C in bash and then exiting

### ISSUE THREAD

**Issue by mrtnbr** [brhahlen/dc#72]
Steps to reproduce:
- Get a shell in a container that has bash
- Press Ctrl-C
- Use ```exit``` command to exit the shell
- You will trigger the fallback to sh

`
maarten@balthasar:~$ dc shell db-backup 
Accessing shell for the following service: db-backup 
[tiredofit/db-backup:4.1.1 07:32:30 /] $ ^C
[tiredofit/db-backup:4.1.1 07:32:33 /] $ exit
exit
/bin/bash not found, falling back to /bin/sh
/ # exit
maarten@balthasar:~$
`

When not pressing Ctrl-C it works as expected:

`
maarten@balthasar:~$ dc shell db-backup 
Accessing shell for the following service: db-backup 
[tiredofit/db-backup:4.1.1 07:34:22 /] $ exit
exit
maarten@balthasar:~$ `

**Comment by brhahlen** [comment]
Fixed in 3.4.5
